from __future__ import annotations

from noema_lab.training.differentiability import (
    TrainingDependencyError,
    sionna_available,
    torch_available,
    require_sionna_available,
    require_torch_available,
)
from noema_lab.training.contracts import (
    CompiledTrainingContract,
    ConstraintSpec,
    NamedValueSpec,
    SignalSpec,
    SlotGroupSpec,
    TensorSpec,
    TrainingContractError,
    TrainingContractOptions,
    compile_training_contract,
    validate_compiled_training_contract,
    write_training_contract_bundle,
)
from noema_lab.training.capture_plan import (
    TrainingCapturePlan,
    TrainingCapturePlanError,
    allocate_split_counts,
    capture_tap_candidates,
    resolve_training_capture_plan,
)
from noema_lab.training.capture_integrity import (
    CaptureSplitFingerprint,
    CaptureSplitIntegrityError,
    assert_disjoint_capture_splits,
    fingerprint_capture_split,
)
from noema_lab.training.channel_estimation_export import (
    CHANNEL_ESTIMATION_LOSS,
    ChannelEstimationExportError,
    ChannelEstimationExportPlan,
    build_channel_estimation_export_plan,
    write_channel_estimation_starter,
)
from noema_lab.training.export_graph import ExportGraph, build_export_graph_from_recipe
from noema_lab.training.delayed_csi_resource_allocation_export import (
    DELAYED_CSI_RESOURCE_ALLOCATION_LOSS,
    DelayedCsiResourceAllocationExportError,
    DelayedCsiResourceAllocationExportPlan,
    build_delayed_csi_resource_allocation_export_plan,
    write_delayed_csi_resource_allocation_starter,
)
from noema_lab.training.exporter import (
    DifferentiableExportError,
    available_exporters,
    export_differentiable_scenario,
    exporter_ids,
    inspect_training_capture,
)
from noema_lab.training.sionna_blocks import (
    AwgnChannelBlock,
    FlatRayleighChannelBlock,
    PowerNormalizationBlock,
    SymbolPowerAllocatorBlock,
    QamPamMapperBlock,
    SionnaAwgnChannelBlock,
    SionnaFlatFadingChannelBlock,
    SionnaMapperBlock,
    SionnaSoftDemapperBlock,
    SoftDemapperBlock,
)

__all__ = [
    "AwgnChannelBlock",
    "ExportGraph",
    "FlatRayleighChannelBlock",
    "PowerNormalizationBlock",
    "SymbolPowerAllocatorBlock",
    "QamPamMapperBlock",
    "SionnaAwgnChannelBlock",
    "SionnaFlatFadingChannelBlock",
    "SionnaMapperBlock",
    "SionnaSoftDemapperBlock",
    "SoftDemapperBlock",
    "TrainingDependencyError",
    "CompiledTrainingContract",
    "ConstraintSpec",
    "NamedValueSpec",
    "SignalSpec",
    "SlotGroupSpec",
    "TensorSpec",
    "TrainingContractError",
    "TrainingContractOptions",
    "TrainingCapturePlan",
    "TrainingCapturePlanError",
    "CaptureSplitFingerprint",
    "CaptureSplitIntegrityError",
    "CHANNEL_ESTIMATION_LOSS",
    "ChannelEstimationExportError",
    "ChannelEstimationExportPlan",
    "DELAYED_CSI_RESOURCE_ALLOCATION_LOSS",
    "DelayedCsiResourceAllocationExportError",
    "DelayedCsiResourceAllocationExportPlan",
    "DifferentiableExportError",
    "available_exporters",
    "allocate_split_counts",
    "assert_disjoint_capture_splits",
    "build_export_graph_from_recipe",
    "build_channel_estimation_export_plan",
    "build_delayed_csi_resource_allocation_export_plan",
    "compile_training_contract",
    "export_differentiable_scenario",
    "exporter_ids",
    "fingerprint_capture_split",
    "capture_tap_candidates",
    "inspect_training_capture",
    "require_sionna_available",
    "require_torch_available",
    "resolve_training_capture_plan",
    "sionna_available",
    "torch_available",
    "validate_compiled_training_contract",
    "write_delayed_csi_resource_allocation_starter",
    "write_channel_estimation_starter",
    "write_training_contract_bundle",
]
