from __future__ import annotations

import copy
import hashlib
import json
import os
from pathlib import Path
import tempfile
import unittest
from unittest import mock

from noema_lab.core import source_closure
from noema_lab.core.source_closure import (
    SourceClosureError,
    build_executable_source_closure,
    verify_executable_source_closure,
)


class ExecutableSourceClosureTests(unittest.TestCase):
    def test_inventory_matches_existing_preparation_schema_and_excludes_only_bytecode(self):
        with tempfile.TemporaryDirectory() as raw:
            root = Path(raw) / "src/noema_lab"
            nested = root / "nested"
            nested.mkdir(parents=True)
            (root / "z.py").write_bytes(b"VALUE = 1\n")
            (nested / "a.txt").write_bytes(b"bound data\n")
            (root / "ignored.pyc").write_bytes(b"generated bytecode")
            (nested / "ignored.PYO").write_bytes(b"generated bytecode")

            closure = build_executable_source_closure(root)

        files = closure["files"]
        self.assertEqual(
            [record["path"] for record in files],
            ["nested/a.txt", "z.py"],
        )
        self.assertEqual(
            closure,
            {
                "schema_version": 1,
                "kind": "noema.executable_source_closure",
                "root": "src/noema_lab",
                "inclusion_policy": (
                    "all_recursive_regular_files_excluding_only_generated_pyc_and_pyo"
                ),
                "excluded_generated_suffixes": [".pyc", ".pyo"],
                "files": files,
                "file_count": 2,
                "python_file_count": 1,
                "total_bytes": len(b"bound data\n") + len(b"VALUE = 1\n"),
                "file_set_sha256": self._canonical_sha256(files),
                "python_file_set_sha256": self._canonical_sha256(
                    [files[1]]
                ),
            },
        )
        self.assertEqual(
            files[0]["sha256"], hashlib.sha256(b"bound data\n").hexdigest()
        )
        self.assertEqual(
            files[1]["sha256"], hashlib.sha256(b"VALUE = 1\n").hexdigest()
        )

    def test_verifier_requires_an_exact_declared_closure(self):
        with tempfile.TemporaryDirectory() as raw:
            root = Path(raw)
            (root / "module.py").write_text("VALUE = 1\n", encoding="utf-8")
            declared = build_executable_source_closure(
                root,
                root_label="test-source",
            )
            self.assertEqual(
                verify_executable_source_closure(
                    declared,
                    root,
                    root_label="test-source",
                ),
                declared,
            )

            changed = copy.deepcopy(declared)
            changed["files"][0]["sha256"] = "0" * 64
            with self.assertRaisesRegex(
                SourceClosureError,
                "declared executable source closure changed",
            ):
                verify_executable_source_closure(
                    changed,
                    root,
                    root_label="test-source",
                )

    def test_symlinks_and_special_nodes_fail_closed(self):
        with tempfile.TemporaryDirectory() as raw:
            root = Path(raw)
            (root / "module.py").write_text("VALUE = 1\n", encoding="utf-8")
            (root / "alias.py").symlink_to(root / "module.py")
            with self.assertRaisesRegex(SourceClosureError, "symlink"):
                build_executable_source_closure(root)

        if not hasattr(os, "mkfifo"):
            self.skipTest("FIFO nodes are unavailable on this platform")
        with tempfile.TemporaryDirectory() as raw:
            root = Path(raw)
            (root / "module.py").write_text("VALUE = 1\n", encoding="utf-8")
            os.mkfifo(root / "unexpected.fifo")
            with self.assertRaisesRegex(SourceClosureError, "special node"):
                build_executable_source_closure(root)

    def test_file_mutation_during_hashing_fails_closed(self):
        with tempfile.TemporaryDirectory() as raw:
            root = Path(raw)
            path = root / "module.py"
            path.write_text("VALUE = 1\n", encoding="utf-8")
            real_hash = source_closure._file_sha256

            def mutate_after_hash(candidate: Path) -> str:
                digest = real_hash(candidate)
                candidate.write_text("VALUE = 22\n", encoding="utf-8")
                return digest

            with (
                mock.patch.object(
                    source_closure,
                    "_file_sha256",
                    side_effect=mutate_after_hash,
                ),
                self.assertRaisesRegex(SourceClosureError, "changed while hashing"),
            ):
                build_executable_source_closure(root)

    def test_repository_inventory_includes_the_helper_itself(self):
        repository_source = Path(__file__).resolve().parents[1] / "src/noema_lab"
        closure = build_executable_source_closure(repository_source)
        paths = [record["path"] for record in closure["files"]]
        self.assertIn("core/source_closure.py", paths)

    @staticmethod
    def _canonical_sha256(value: object) -> str:
        encoded = json.dumps(
            value,
            sort_keys=True,
            separators=(",", ":"),
            ensure_ascii=False,
            allow_nan=False,
        ).encode("utf-8")
        return hashlib.sha256(encoded).hexdigest()


if __name__ == "__main__":
    unittest.main()
