"""Attach one repository demo trainer to an existing neutral Noema contract.

This is demonstration tooling, not part of the Noema training interface.  The
Workbench remains architecture-, objective-, and trainer-neutral; a tutorial
invokes this helper only when it wants to reproduce one of the checked-in demos.
"""

from __future__ import annotations

import argparse
import hashlib
import math
import shlex
import stat
import sys
from pathlib import Path
from typing import Any, Dict, Mapping

import yaml

from noema_lab.core.matrix import canonicalize_recipe_matrix, matrix_values_for_step_param
from noema_lab.core.recipes import load_recipe
from noema_lab.core.structured_input import load_strict_yaml_or_json
from noema_lab.core.training_plans import (
    TrainingPlan,
    apply_training_plan,
    load_training_plan,
    training_plan_fingerprint,
)
from noema_lab.ops import build_registry
from noema_lab.training.csi_feedback_export import CSI_FEEDBACK_EXAMPLE_LOSS
from noema_lab.training.channel_estimation_export import CHANNEL_ESTIMATION_LOSS
from noema_lab.training.delayed_csi_resource_allocation_export import (
    DELAYED_CSI_RESOURCE_ALLOCATION_LOSS,
)
from noema_lab.training.exporter import (
    ExportOptions,
    _attach_optional_starter,
    select_differentiable_exporter,
)
from noema_lab.training.image_data_export import (
    build_image_file_data_plan,
    write_image_file_data_contract,
)
from noema_lab.training.generic_capture_export import (
    write_generic_capture_data_contract,
)
from noema_lab.training.modulation_recognition_export import MODULATION_CLASSIFICATION_LOSS
from noema_lab.training.neural_receiver_export import NEURAL_RECEIVER_CAPTURE_SNR_DB
from noema_lab.training.phase_tracking_receiver_export import (
    PHASE_TRACKING_CAPTURE_SNR_DB,
)
from noema_lab.training.resource_allocation_export import RESOURCE_ALLOCATION_LOSS
from noema_lab.training.standalone_input import (
    STANDALONE_STRUCTURED_INPUT_FILENAME,
    standalone_structured_input_source,
)


DEMO_LOSSES = {
    "csi-feedback": CSI_FEEDBACK_EXAMPLE_LOSS,
    "delayed-csi-resource-allocation": DELAYED_CSI_RESOURCE_ALLOCATION_LOSS,
    "deepjscc-image": "image.mse",
    "modulation-recognition": MODULATION_CLASSIFICATION_LOSS,
    "mimo-ofdm-channel-estimation": CHANNEL_ESTIMATION_LOSS,
    "neural-receiver": "bit.bce",
    "phase-tracking-receiver": "bit.bce",
    "resource-allocation": RESOURCE_ALLOCATION_LOSS,
}

DEMO_HANDOFF_MARKER = (
    "Generated by demo_trainings/prepare_example.py; non-normative demo handoff."
)
DEMO_HANDOFF_FILES = ("RUN_DEMO.md", "train_demo.py", "evaluate_demo.py")


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _mapping(path: Path) -> Dict[str, Any]:
    value = load_strict_yaml_or_json(path)
    if not isinstance(value, Mapping):
        raise ValueError("Expected a YAML object: %s" % path)
    return dict(value)


def _bundle_result(bundle: Path) -> Dict[str, Any]:
    manifest = _mapping(bundle / "project_manifest.yaml")
    if str(manifest.get("kind") or "") != "noema.training_interface_bundle@1":
        raise ValueError("Not a neutral Noema training-interface bundle: %s" % bundle)
    contract = _mapping(bundle / "training_contract.yaml")
    graph_contract = dict((manifest.get("contracts") or {}).get("scenario_graph") or {})
    slot_contract = dict((manifest.get("contracts") or {}).get("trainable_slots") or {})
    data_contract_path = bundle / "data_contract.yaml"
    return {
        "status": "exported",
        "kind": str(manifest.get("kind") or ""),
        "out_dir": str(bundle),
        "contract_id": str(contract.get("id") or ""),
        "contract_sha256": str(slot_contract.get("sha256") or ""),
        "contract_file_sha256": str(slot_contract.get("file_sha256") or _sha256(bundle / "training_contract.yaml")),
        "scenario_graph_sha256": str(graph_contract.get("sha256") or ""),
        "scenario_graph_file_sha256": str(graph_contract.get("file_sha256") or _sha256(bundle / "scenario_graph.json")),
        "project_manifest": manifest,
        "data_contract": _mapping(data_contract_path) if data_contract_path.is_file() else {},
        "files": [str(path.relative_to(bundle)) for path in bundle.rglob("*") if path.is_file()],
    }


def prepare_example(bundle: Path, demo: str, *, project_root: Path) -> Path:
    bundle = bundle.resolve()
    demo_id = str(demo or "").strip()
    if demo_id not in DEMO_LOSSES:
        raise ValueError("Unknown demo %r; choose one of %s" % (demo_id, ", ".join(sorted(DEMO_LOSSES))))
    _require_safe_demo_handoff_paths(bundle)
    recipe, training_plan = _load_planned_recipe(bundle)
    if not training_plan.selected_steps:
        raise ValueError("The exported training plan has no selected replacement blocks")
    registry = build_registry()
    if demo_id == "phase-tracking-receiver":
        recipe, training_plan, capture_enrichments = (
            _ensure_phase_tracking_demo_capture_plan(
                bundle,
                recipe,
                training_plan,
                registry=registry,
                project_root=project_root.resolve(),
            )
        )
        if capture_enrichments:
            additions = " and ".join(capture_enrichments)
            print(
                "phase-tracking demo updated its generated capture plan with %s; "
                "recapture train, validation, "
                "and held-out test before training." % additions
            )
    elif demo_id == "delayed-csi-resource-allocation":
        recipe, training_plan, capture_enrichments = (
            _ensure_delayed_csi_allocation_demo_capture_plan(
                bundle,
                recipe,
                training_plan,
                registry=registry,
                project_root=project_root.resolve(),
            )
        )
        if capture_enrichments:
            print(
                "delayed-CSI allocation demo added %s; recapture train, "
                "validation, and held-out test before training."
                % " and ".join(capture_enrichments)
            )
    options = ExportOptions(
        optimizable_steps=list(training_plan.selected_steps),
        loss=DEMO_LOSSES[demo_id],
        framework="torch",
        exporter=demo_id,
        project_root=project_root.resolve(),
        include_starter=True,
    )
    exporter = select_differentiable_exporter(recipe, registry, options)
    plan = exporter.build_plan(recipe, registry, options)
    if demo_id == "deepjscc-image":
        _ensure_deepjscc_demo_data_contract(
            bundle,
            plan,
            project_root=project_root.resolve(),
        )
    bundle_result = _bundle_result(bundle)
    _require_demo_signals(bundle_result, plan, demo_id)
    if demo_id == "neural-receiver":
        _require_neural_receiver_capture_sweep(bundle)
    elif demo_id == "phase-tracking-receiver":
        _require_phase_tracking_capture_sweep(bundle)
    training_project = bundle / "reference_training"
    starter_payload = exporter.write_export(
        plan,
        training_project,
        force=True,
    )
    _attach_optional_starter(
        bundle_result,
        starter_payload,
        destination=bundle,
        selected_exporter=exporter.id,
    )
    _write_root_demo_handoff(
        bundle,
        demo_id,
        project_root=project_root.resolve(),
    )
    return training_project


def _load_planned_recipe(bundle: Path) -> tuple[Any, Any]:
    """Rejoin the neutral scenario and its external training intent.

    Training-interface bundles deliberately store these separately.  Demo
    exporters need the transient joined view so they preserve researcher-chosen
    capture IDs instead of falling back to their suggested labels.
    """

    neutral_recipe = load_recipe(bundle / "noema_recipe.yaml")
    training_plan = load_training_plan(bundle / "training_plan.yaml")
    return apply_training_plan(neutral_recipe, training_plan), training_plan


def _ensure_phase_tracking_demo_capture_plan(
    bundle: Path,
    recipe: Any,
    training_plan: TrainingPlan,
    *,
    registry: Any,
    project_root: Path,
) -> tuple[Any, TrainingPlan, tuple[str, ...]]:
    """Add the reference demo's capture requirements after explicit attachment.

    The runnable scenario and generic Workbench remain neutral.  Invoking this
    specific demo is the point at which its auxiliary objective becomes known,
    so only the generated external training plan and Noema-owned capture assets
    are enriched.  Existing captured shards and researcher artifacts are never
    removed.
    """

    selected = set(training_plan.selected_steps)
    receivers = [
        step
        for step in recipe.steps
        if step.id in selected
        and step.op == "demodulation.phase_tracking_receiver_adapter"
    ]
    if len(receivers) != 1:
        return recipe, training_plan, ()
    phase_truth_reference = str(
        receivers[0].inputs.get("phase_truth") or ""
    ).strip()
    if not phase_truth_reference:
        return recipe, training_plan, ()

    capture = dict(training_plan.dataset_capture or {})
    raw_taps = capture.get("taps")
    if raw_taps is None:
        taps: list[Dict[str, Any]] = []
    elif isinstance(raw_taps, list):
        if any(not isinstance(item, Mapping) for item in raw_taps):
            raise ValueError(
                "training_plan.dataset_capture.taps entries must be objects"
            )
        taps = [dict(item) for item in raw_taps]
    else:
        raise ValueError("training_plan.dataset_capture.taps must be a list")
    phase_target_present = any(
        isinstance(item, Mapping)
        and str(item.get("from") or "") == phase_truth_reference
        for item in taps
    )
    additions: list[str] = []
    if not phase_target_present:
        existing_ids = {
            str(item.get("id") or "")
            for item in taps
            if isinstance(item, Mapping)
        }
        tap_id = _unique_demo_capture_tap_id(
            phase_truth_reference,
            existing_ids,
        )
        taps.append({"id": tap_id, "from": phase_truth_reference})
        capture["taps"] = taps
        additions.append("its training-only carrier-phase target")

    expected_sweep = tuple(float(value) for value in PHASE_TRACKING_CAPTURE_SNR_DB)
    canonical_matrix = canonicalize_recipe_matrix(recipe)
    matrix_snr = _finite_numeric_sequence(
        matrix_values_for_step_param(recipe, "wireless_channel", "snr_db")
    )
    raw_sweep = capture.get("sweep")
    if canonical_matrix.enabled:
        if matrix_snr != expected_sweep:
            rendered = "missing" if matrix_snr is None else repr(matrix_snr)
            raise ValueError(
                "The phase-tracking receiver demonstration requires the recipe "
                "matrix to define wireless_channel.snr_db = [-2, 2, 6, 10]; "
                "the source matrix declares %s." % rendered
            )
        if raw_sweep is not None:
            equivalent = (
                isinstance(raw_sweep, Mapping)
                and set(str(key) for key in raw_sweep)
                == {"wireless_channel.snr_db"}
                and _finite_numeric_sequence(
                    raw_sweep.get("wireless_channel.snr_db")
                )
                == expected_sweep
            )
            if not equivalent:
                raise ValueError(
                    "The phase-tracking receiver capture plan cannot combine its "
                    "recipe matrix with a different dataset_capture.sweep. Keep "
                    "metadata.matrix as the single SNR variant definition."
                )
            capture.pop("sweep", None)
            additions.append(
                "the recipe matrix as its single SNR variant definition"
            )
    elif raw_sweep is None:
        capture["sweep"] = {
            "wireless_channel.snr_db": [
                int(value) if float(value).is_integer() else float(value)
                for value in expected_sweep
            ]
        }
        additions.append("the SNR capture sweep [-2, 2, 6, 10]")
    elif isinstance(raw_sweep, Mapping):
        configured_snr = raw_sweep.get("wireless_channel.snr_db")
        if configured_snr is None:
            updated_sweep = dict(raw_sweep)
            updated_sweep["wireless_channel.snr_db"] = [
                int(value) if float(value).is_integer() else float(value)
                for value in expected_sweep
            ]
            capture["sweep"] = updated_sweep
            additions.append("the SNR capture sweep [-2, 2, 6, 10]")
        elif _finite_numeric_sequence(configured_snr) != expected_sweep:
            # Preserve researcher intent. The existing frozen-sweep validator
            # below will report the exact conflict without rewriting the bundle.
            return recipe, training_plan, ()
    else:
        # Ordered assignment sweeps are explicit researcher intent. The demo's
        # existing validator will explain that they do not match its benchmark.
        return recipe, training_plan, ()

    if not additions:
        return recipe, training_plan, ()
    enriched_plan = TrainingPlan(
        selected_steps=training_plan.selected_steps,
        loss_steps=training_plan.loss_steps,
        dataset_capture=capture,
        objective=training_plan.objective,
        starter=training_plan.starter,
        framework=training_plan.framework,
        extra_fields=training_plan.extra_fields,
    )
    enriched_recipe = apply_training_plan(recipe, enriched_plan)

    data = write_generic_capture_data_contract(
        enriched_recipe,
        registry,
        selected_step_ids=list(enriched_plan.selected_steps),
        out_dir=bundle,
        project_root=project_root,
    )
    training_plan_path = bundle / "training_plan.yaml"
    training_plan_path.write_text(
        yaml.safe_dump(enriched_plan.to_dict(), sort_keys=False),
        encoding="utf-8",
    )
    manifest_path = bundle / "project_manifest.yaml"
    manifest = _mapping(manifest_path)
    manifest["capture_jobs"] = list(data.get("capture_jobs") or [])
    contract = dict(data.get("data_contract") or {})
    manifest["data_contract"] = {
        "path": "data_contract.yaml",
        "kind": "noema.training_data_contract@1",
        "sha256": str(data.get("data_contract_sha256") or ""),
        "file_sha256": str(data.get("data_contract_file_sha256") or ""),
        "ownership": dict(contract.get("ownership") or {}),
    }
    manifest["training_plan"] = {
        "path": "training_plan.yaml",
        "sha256": training_plan_fingerprint(enriched_plan),
    }
    manifest_path.write_text(
        yaml.safe_dump(manifest, sort_keys=False),
        encoding="utf-8",
    )
    return enriched_recipe, enriched_plan, tuple(additions)


def _unique_demo_capture_tap_id(
    reference: str,
    existing_ids: set[str],
) -> str:
    base = "".join(
        character if character.isalnum() or character == "_" else "_"
        for character in str(reference)
    ).strip("_") or "phase_truth"
    candidate = base
    suffix = 2
    while candidate in existing_ids:
        candidate = "%s_%d" % (base, suffix)
        suffix += 1
    return candidate


def _ensure_delayed_csi_allocation_demo_capture_plan(
    bundle: Path,
    recipe: Any,
    training_plan: TrainingPlan,
    *,
    registry: Any,
    project_root: Path,
) -> tuple[Any, TrainingPlan, tuple[str, ...]]:
    """Attach the demo-only current-CSI outcome without changing the recipe.

    The allocator ABI itself requires only delayed transmitter CSI.  Invoking
    this optional example is the point where aligned current CSI becomes known
    as an auxiliary loss input, so it belongs in the generated training plan
    rather than in the portable model interface.
    """

    selected = set(training_plan.selected_steps)
    allocators = [
        step
        for step in recipe.steps
        if step.id in selected
        and step.op
        in {
            "model.symbol_power_allocator",
            "model.causal_csi_power_allocator",
        }
    ]
    if len(allocators) != 1:
        return recipe, training_plan, ()
    delayed_reference = str(
        allocators[0].inputs.get("channel_state") or ""
    ).strip()
    if "." not in delayed_reference:
        return recipe, training_plan, ()
    observation_id, observation_output = delayed_reference.split(".", 1)
    if observation_output != "transmitter_csi":
        return recipe, training_plan, ()
    observation = next(
        (step for step in recipe.steps if step.id == observation_id),
        None,
    )
    if observation is None or observation.op != "wireless.ofdm_delayed_csi":
        return recipe, training_plan, ()
    current_reference = "%s.actual_state" % observation.id

    capture = dict(training_plan.dataset_capture or {})
    raw_taps = capture.get("taps")
    if raw_taps is None:
        taps: list[Dict[str, Any]] = []
    elif isinstance(raw_taps, list):
        if any(not isinstance(item, Mapping) for item in raw_taps):
            raise ValueError(
                "training_plan.dataset_capture.taps entries must be objects"
            )
        taps = [dict(item) for item in raw_taps]
    else:
        raise ValueError("training_plan.dataset_capture.taps must be a list")

    if any(
        str(item.get("from") or "") == current_reference for item in taps
    ):
        return recipe, training_plan, ()
    tap_id = _unique_demo_capture_tap_id(
        current_reference,
        {
            str(item.get("id") or "")
            for item in taps
            if isinstance(item, Mapping)
        },
    )
    taps.append({"id": tap_id, "from": current_reference})
    capture["taps"] = taps
    enriched_plan = TrainingPlan(
        selected_steps=training_plan.selected_steps,
        loss_steps=training_plan.loss_steps,
        dataset_capture=capture,
        objective=training_plan.objective,
        starter=training_plan.starter,
        framework=training_plan.framework,
        extra_fields=training_plan.extra_fields,
    )
    enriched_recipe = apply_training_plan(recipe, enriched_plan)
    data = write_generic_capture_data_contract(
        enriched_recipe,
        registry,
        selected_step_ids=list(enriched_plan.selected_steps),
        out_dir=bundle,
        project_root=project_root,
    )

    training_plan_path = bundle / "training_plan.yaml"
    training_plan_path.write_text(
        yaml.safe_dump(enriched_plan.to_dict(), sort_keys=False),
        encoding="utf-8",
    )
    manifest_path = bundle / "project_manifest.yaml"
    manifest = _mapping(manifest_path)
    manifest["capture_jobs"] = list(data.get("capture_jobs") or [])
    contract = dict(data.get("data_contract") or {})
    manifest["data_contract"] = {
        "path": "data_contract.yaml",
        "kind": "noema.training_data_contract@1",
        "sha256": str(data.get("data_contract_sha256") or ""),
        "file_sha256": str(data.get("data_contract_file_sha256") or ""),
        "ownership": dict(contract.get("ownership") or {}),
    }
    manifest["training_plan"] = {
        "path": "training_plan.yaml",
        "sha256": training_plan_fingerprint(enriched_plan),
    }
    manifest_path.write_text(
        yaml.safe_dump(manifest, sort_keys=False),
        encoding="utf-8",
    )
    return (
        enriched_recipe,
        enriched_plan,
        ("its aligned training-only current-CSI outcome",),
    )


def _require_safe_demo_handoff_paths(bundle: Path) -> None:
    """Refuse to replace root files that were not created by this helper."""

    for relative in DEMO_HANDOFF_FILES:
        path = bundle / relative
        if not path.exists():
            continue
        if not path.is_file():
            raise ValueError(
                "Cannot attach the demo because %s exists and is not a regular file" % path
            )
        try:
            existing = path.read_text(encoding="utf-8")
        except (OSError, UnicodeError) as exc:
            raise ValueError(
                "Cannot verify ownership of existing demo handoff file %s" % path
            ) from exc
        if DEMO_HANDOFF_MARKER not in existing[:512]:
            raise ValueError(
                "Refusing to overwrite researcher-owned file %s. Rename it or choose a "
                "different bundle directory before attaching the published demo." % path
            )


def _demo_launcher(target_name: str) -> str:
    template = '''#!/usr/bin/env python3
# __MARKER__
"""Run the attached published demo from the training-bundle root."""

import subprocess
import sys
from pathlib import Path

from structured_input import load_strict_yaml_or_json


def _load_manifest(bundle):
    path = bundle / "project_manifest.yaml"
    if not path.is_file():
        return {}
    try:
        payload = load_strict_yaml_or_json(path)
    except Exception as exc:
        print(
            "Cannot read the training-bundle manifest: %s" % exc,
            file=sys.stderr,
        )
        return None
    return payload if isinstance(payload, dict) else {}


def _capture_jobs(manifest):
    jobs = manifest.get("capture_jobs") or []
    if jobs:
        return [item for item in jobs if isinstance(item, dict)]
    scaffold = (
        ((manifest.get("external_training") or {}).get("optional_demo_scaffold") or {})
    )
    return [
        item
        for item in (scaffold.get("capture_jobs") or [])
        if isinstance(item, dict)
    ]


def _bundle_path(bundle, manifest, configured, fallback):
    raw_value = str(configured or "").strip()
    if not raw_value:
        return bundle / fallback
    value = Path(raw_value)
    out_dir = Path(str(manifest.get("out_dir") or ""))
    if str(value) and str(out_dir):
        try:
            return bundle / value.relative_to(out_dir)
        except ValueError:
            pass
    if str(value) and not value.is_absolute() and len(value.parts) <= 2:
        return bundle / value
    return bundle / fallback


def _returned_artifact_path(bundle, manifest):
    scaffold = (
        ((manifest.get("external_training") or {}).get("optional_demo_scaffold") or {})
    )
    training = scaffold.get("training") or {}
    configured = training.get("artifact_manifest_path")
    if not configured:
        for item in manifest.get("trained_artifacts") or []:
            if isinstance(item, dict) and item.get("manifest_path"):
                configured = item.get("manifest_path")
                break
    return _bundle_path(
        bundle,
        manifest,
        configured,
        Path("trained_artifact.yaml"),
    )


def _capture_schema_path(bundle, manifest, job, split):
    directory = _bundle_path(
        bundle,
        manifest,
        job.get("output_dir"),
        Path("data") / split,
    )
    return directory / "schema.json"


def _expected_tap_labels(job):
    labels = []
    for tap in job.get("expected_taps") or []:
        if not isinstance(tap, dict):
            continue
        label = str(tap.get("from") or tap.get("id") or "").strip()
        if label and label not in labels:
            labels.append(label)
    return labels


def _missing_taps(schema, job):
    tap_schemas = schema.get("tap_schemas") or {}
    if not isinstance(tap_schemas, dict):
        tap_schemas = {}
    present_ids = set(str(value) for value in tap_schemas)
    present_references = set()
    for value in tap_schemas.values():
        if isinstance(value, dict) and value.get("from"):
            present_references.add(str(value.get("from")))
    missing = []
    for tap in job.get("expected_taps") or []:
        if not isinstance(tap, dict):
            continue
        tap_id = str(tap.get("id") or "")
        reference = str(tap.get("from") or "")
        if tap_id not in present_ids and reference not in present_references:
            missing.append(reference or tap_id)
    return missing


def _capture_preflight(bundle, manifest, target_name):
    required_splits = (
        ("test",) if target_name == "evaluate.py" else ("train", "validation")
    )
    jobs = _capture_jobs(manifest)
    if not jobs:
        return True
    by_split = {str(item.get("split") or ""): item for item in jobs}
    requirements = []
    problems = []
    for split in required_splits:
        job = by_split.get(split)
        if job is None:
            problems.append("%s capture job is missing from project_manifest.yaml" % split)
            continue
        label = str(job.get("label") or split.replace("_", " ").title())
        expected = int(job.get("requested_samples") or 0)
        unit = str(job.get("sample_unit") or "records")
        taps = _expected_tap_labels(job)
        count_text = ("%s %s" % (format(expected, ",d"), unit)) if expected else unit
        tap_text = ", ".join(taps) if taps else "the contract taps"
        requirements.append("%s: %s; taps: %s" % (label, count_text, tap_text))
        schema_path = _capture_schema_path(bundle, manifest, job, split)
        if not schema_path.is_file():
            problems.append("%s has not been captured (%s is missing)" % (label, schema_path))
            continue
        try:
            schema = load_strict_yaml_or_json(schema_path)
        except Exception as exc:
            problems.append("%s capture schema cannot be read: %s" % (label, exc))
            continue
        captured = int(schema.get("captured_samples") or 0)
        if expected and captured < expected:
            problems.append(
                "%s contains %s of %s required %s"
                % (label, format(captured, ",d"), format(expected, ",d"), unit)
            )
        missing = _missing_taps(schema, job)
        if missing:
            problems.append("%s is missing tap(s): %s" % (label, ", ".join(missing)))
    if not problems:
        return True
    action = "evaluate" if target_name == "evaluate.py" else "train"
    print("The captured datasets are not ready to %s this demo." % action, file=sys.stderr)
    print(
        "Return to Workbench > Dataset capture, select Capture all datasets "
        "(or Recapture all datasets), and wait for:",
        file=sys.stderr,
    )
    for requirement in requirements:
        print("  - %s" % requirement, file=sys.stderr)
    print("Missing or incomplete:", file=sys.stderr)
    for problem in problems:
        print("  - %s" % problem, file=sys.stderr)
    print(
        "Then rerun %s." % ("evaluate_demo.py" if target_name == "evaluate.py" else "train_demo.py"),
        file=sys.stderr,
    )
    return False


def main():
    command_name = Path(__file__).name
    if sys.version_info < (3, 11) or sys.version_info >= (3, 14):
        print(
            "This demo requires Python 3.11 through 3.13. From this directory run: "
            "uv run --extra onnx python %s" % command_name,
            file=sys.stderr,
        )
        return 2
    bundle = Path(__file__).resolve().parent
    target_name = "__TARGET__"
    target = bundle / "reference_training" / target_name
    if not target.is_file():
        print(
            "Attached demo script is missing: %s. Rerun demo_trainings/prepare_example.py."
            % target,
            file=sys.stderr,
        )
        return 2
    manifest = _load_manifest(bundle)
    if manifest is None:
        return 2
    if target_name == "evaluate.py":
        artifact = _returned_artifact_path(bundle, manifest)
        if not artifact.is_file():
            print("No trained model is available to evaluate.", file=sys.stderr)
            print(
                "Run train_demo.py successfully first. Expected returned artifact: %s"
                % artifact,
                file=sys.stderr,
            )
            return 2
    if not _capture_preflight(bundle, manifest, target_name):
        return 2
    return subprocess.call(
        [sys.executable, str(target)] + sys.argv[1:],
        cwd=str(target.parent),
    )


if __name__ == "__main__":
    raise SystemExit(main())
'''
    return template.replace("__MARKER__", DEMO_HANDOFF_MARKER).replace(
        "__TARGET__", target_name
    )


def _manifest_capture_jobs(manifest: Mapping[str, Any]) -> list[Dict[str, Any]]:
    """Return the capture jobs that govern the attached demo handoff."""

    raw_jobs = manifest.get("capture_jobs") or []
    if not raw_jobs:
        scaffold = (
            ((manifest.get("external_training") or {}).get("optional_demo_scaffold") or {})
        )
        raw_jobs = scaffold.get("capture_jobs") or []
    if not isinstance(raw_jobs, (list, tuple)):
        return []
    return [dict(item) for item in raw_jobs if isinstance(item, Mapping)]


def _demo_quickstart(
    demo_id: str,
    *,
    capture_jobs: list[Dict[str, Any]],
    project_root: Path,
) -> str:
    if capture_jobs:
        data_readiness = """Before training, return to **Workbench** > **Dataset capture**, select **Capture all datasets**
(or **Recapture all datasets**), and wait for every split to report its requested count. Only then,
from **this bundle directory**, run the trainer:"""
        evaluation_scope = """`train_demo.py` runs `reference_training/train.py` on the train split and uses the validation split
for checkpoint selection. `evaluate_demo.py` then evaluates that selected checkpoint once on the
held-out test split."""
        evaluator_intro = "run the held-out evaluator:"
        validation_distinction = "held-out evaluation"
    else:
        data_readiness = """No dataset capture is required for this bundle. Its exported data contract already pins the data
used by the example. From **this bundle directory**, run the trainer:"""
        evaluation_scope = """`train_demo.py` runs `reference_training/train.py` with the training and validation data pinned by
the exported data contract. `evaluate_demo.py` then runs the example's declared evaluation."""
        evaluator_intro = "run the example evaluator:"
        validation_distinction = "model-quality evaluation"

    project = shlex.quote(str(Path(project_root).resolve()))
    return """<!-- {marker} -->
# Run the attached `{demo}` demonstration

This file and the two launchers below were added only because the published demonstration was
explicitly attached. They are example code, not part of the normative Noema training contract.

{data_readiness}

```bash
uv run --project {project} --extra onnx python train_demo.py
```

After training finishes successfully and creates `trained_artifact.yaml`, {evaluator_intro}

```bash
uv run --project {project} --extra onnx python evaluate_demo.py
```

{evaluation_scope}

Finally, return to Workbench and select **Validate returned model** to check the
artifact interface and integrity. That Workbench check is different from {validation_distinction}.

If this bundle is no longer inside the Noema checkout, use a Python 3.11-through-3.13 environment with
the packages in `reference_training/requirements.txt` installed, then replace the `uv run --project
... --extra onnx python` prefix with that environment's Python executable.
""".format(
        marker=DEMO_HANDOFF_MARKER,
        demo=demo_id,
        data_readiness=data_readiness,
        evaluation_scope=evaluation_scope,
        evaluator_intro=evaluator_intro,
        validation_distinction=validation_distinction,
        project=project,
    )


def _write_root_demo_handoff(
    bundle: Path,
    demo_id: str,
    *,
    project_root: Path | None = None,
) -> None:
    """Add safe root launchers and record their non-normative ownership."""

    _require_safe_demo_handoff_paths(bundle)
    resolved_project_root = (
        Path(project_root).resolve()
        if project_root is not None
        else Path(__file__).resolve().parents[1]
    )
    manifest_path = bundle / "project_manifest.yaml"
    manifest = _mapping(manifest_path)
    external_training = dict(manifest.get("external_training") or {})
    scaffold = dict(external_training.get("optional_demo_scaffold") or {})
    if not scaffold.get("included"):
        raise ValueError(
            "The optional demonstration scaffold was not recorded in %s" % manifest_path
        )
    support_path = bundle / STANDALONE_STRUCTURED_INPUT_FILENAME
    support_source = standalone_structured_input_source()
    if support_path.exists():
        if not support_path.is_file() or support_path.read_text(
            encoding="utf-8"
        ) != support_source:
            raise ValueError(
                "Refusing to overwrite researcher-owned strict-input helper %s"
                % support_path
            )
    support_path.write_text(support_source, encoding="utf-8")
    payloads = {
        "RUN_DEMO.md": _demo_quickstart(
            demo_id,
            capture_jobs=_manifest_capture_jobs(manifest),
            project_root=resolved_project_root,
        ),
        "train_demo.py": _demo_launcher("train.py"),
        "evaluate_demo.py": _demo_launcher("evaluate.py"),
    }
    for relative, payload in payloads.items():
        path = bundle / relative
        path.write_text(payload, encoding="utf-8")
        if path.suffix == ".py":
            path.chmod(path.stat().st_mode | stat.S_IXUSR)

    scaffold["root_handoff"] = {
        "ownership": "noema_demo_helper",
        "normative": False,
        "working_directory": ".",
        "quickstart": "RUN_DEMO.md",
        "training": {
            "path": "train_demo.py",
            "command": "python train_demo.py",
            "target": "reference_training/train.py",
        },
        "evaluation": {
            "path": "evaluate_demo.py",
            "command": "python evaluate_demo.py",
            "target": "reference_training/evaluate.py",
        },
        "managed_files": [
            {"path": relative, "sha256": _sha256(bundle / relative)}
            for relative in DEMO_HANDOFF_FILES
        ],
        "support_files": [
            {
                "path": STANDALONE_STRUCTURED_INPUT_FILENAME,
                "sha256": _sha256(support_path),
            }
        ],
    }
    external_training["optional_demo_scaffold"] = scaffold
    manifest["external_training"] = external_training
    manifest_path.write_text(
        yaml.safe_dump(manifest, sort_keys=False),
        encoding="utf-8",
    )


def _ensure_deepjscc_demo_data_contract(
    bundle: Path,
    plan: Any,
    *,
    project_root: Path,
) -> None:
    """Materialize the example's image split without changing recipe identity."""

    if (bundle / "data_contract.yaml").is_file():
        return
    image_plan = build_image_file_data_plan(
        plan.recipe,
        plan.data_step,
        project_root=project_root,
    )
    data = write_image_file_data_contract(image_plan, bundle)
    manifest_path = bundle / "project_manifest.yaml"
    manifest = _mapping(manifest_path)
    manifest["data_contract"] = {
        "path": "data_contract.yaml",
        "kind": "noema.training_data_contract@1",
        "sha256": str(data.get("data_contract_sha256") or ""),
        "file_sha256": str(data.get("data_contract_file_sha256") or ""),
        "ownership": dict((data.get("data_contract") or {}).get("ownership") or {}),
    }
    manifest["capture_jobs"] = []
    manifest_path.write_text(
        yaml.safe_dump(manifest, sort_keys=False),
        encoding="utf-8",
    )


def _require_demo_signals(bundle_result: Mapping[str, Any], plan: Any, demo: str) -> None:
    """Validate only the checked-in example's needs, never the generic contract."""

    expected: list[str] = []
    if demo == "resource-allocation":
        expected = [str(plan.feature_reference)]
    elif demo == "delayed-csi-resource-allocation":
        expected = [
            str(plan.delayed_csi_reference),
            str(plan.current_csi_reference),
        ]
    elif demo == "csi-feedback":
        expected = [str(plan.true_csi_reference)]
    elif demo == "mimo-ofdm-channel-estimation":
        expected = [
            str(plan.pilot_reference),
            str(plan.mask_reference),
            str(plan.feature_reference),
            str(plan.noise_reference),
            str(plan.target_reference),
        ]
    elif demo == "phase-tracking-receiver":
        expected = [
            str(plan.feature_reference),
            str(plan.pilot_context_reference),
            str(plan.target_reference),
        ]
    elif demo in {"neural-receiver", "modulation-recognition"}:
        expected = [str(plan.feature_reference), str(plan.target_reference)]
    if not expected:
        return
    signals = list((bundle_result.get("data_contract") or {}).get("signals") or [])
    available = {
        str(item.get("reference") or "")
        for item in signals
        if isinstance(item, Mapping)
    }
    missing = [reference for reference in expected if reference not in available]
    if missing:
        raise ValueError(
            "The %s demonstration project needs captured signal(s) %s. In Workbench > "
            "Dataset definition > Captured signals, select them, enable Overwrite generated "
            "files, and export the training bundle again. Then rerun this helper and recapture "
            "the datasets before training. This requirement belongs to the demonstration, "
            "not the recipe."
            % (demo, ", ".join(missing))
        )


def _require_neural_receiver_capture_sweep(bundle: Path) -> None:
    """Require one consistent SNR-variant source in every frozen capture asset."""

    expected = tuple(float(value) for value in NEURAL_RECEIVER_CAPTURE_SNR_DB)
    source_path = bundle / "noema_recipe.yaml"
    if not source_path.is_file():
        raise ValueError(
            "The neural-receiver bundle is missing noema_recipe.yaml. "
            "Export the training bundle again before attaching the demo."
        )
    source_recipe = load_recipe(source_path)
    source_matrix = canonicalize_recipe_matrix(source_recipe)
    source_matrix_snr = _finite_numeric_sequence(
        matrix_values_for_step_param(
            source_recipe,
            "wireless_channel",
            "snr_db",
        )
    )
    matrix_is_authoritative = source_matrix.enabled
    problems = []
    if matrix_is_authoritative and source_matrix_snr != expected:
        rendered = (
            "missing" if source_matrix_snr is None else repr(source_matrix_snr)
        )
        problems.append("noema_recipe.yaml matrix declares %s" % rendered)

    plan_path = bundle / "training_plan.yaml"
    if not plan_path.is_file():
        problems.append("training_plan.yaml is missing")
    else:
        plan_payload = _mapping(plan_path)
        plan_capture = plan_payload.get("dataset_capture") or {}
        plan_sweep = (
            plan_capture.get("sweep")
            if isinstance(plan_capture, Mapping)
            else None
        )
        plan_snr = _finite_numeric_sequence(
            plan_sweep.get("wireless_channel.snr_db")
            if isinstance(plan_sweep, Mapping)
            else None
        )
        if matrix_is_authoritative:
            if plan_sweep is not None:
                problems.append(
                    "training_plan.yaml redundantly declares dataset_capture.sweep"
                )
        elif plan_snr != expected:
            rendered = "missing" if plan_snr is None else repr(plan_snr)
            problems.append("training_plan.yaml sweep declares %s" % rendered)

    for relative in (
        "capture_train_recipe.yaml",
        "capture_validation_recipe.yaml",
        "capture_test_recipe.yaml",
    ):
        path = bundle / relative
        if not path.is_file():
            problems.append("%s is missing" % relative)
            continue
        capture_recipe = load_recipe(path)
        capture_matrix = canonicalize_recipe_matrix(capture_recipe)
        matrix_snr = _finite_numeric_sequence(
            matrix_values_for_step_param(
                capture_recipe,
                "wireless_channel",
                "snr_db",
            )
        )
        capture_config = dict(capture_recipe.dataset_capture or {})
        raw_sweep = capture_config.get("sweep")
        sweep_snr = _finite_numeric_sequence(
            raw_sweep.get("wireless_channel.snr_db")
            if isinstance(raw_sweep, Mapping)
            else None
        )
        if matrix_is_authoritative:
            if not capture_matrix.enabled or matrix_snr != expected:
                rendered = "missing" if matrix_snr is None else repr(matrix_snr)
                problems.append("%s matrix declares %s" % (relative, rendered))
            if raw_sweep is not None:
                problems.append(
                    "%s also declares dataset_capture.sweep" % relative
                )
        else:
            if capture_matrix.enabled:
                problems.append("%s unexpectedly declares metadata.matrix" % relative)
            if sweep_snr != expected:
                rendered = "missing" if sweep_snr is None else repr(sweep_snr)
                problems.append("%s sweep declares %s" % (relative, rendered))

    if problems:
        raise ValueError(
            "The neural-receiver demonstration requires exactly one "
            "wireless_channel.snr_db variant definition with values "
            "[-2, 2, 6, 10]. This bundle is not ready: %s. Leave Capture "
            "coordinates blank for the built-in matrix template, enable "
            "Overwrite generated files, export the training bundle again, and "
            "recapture all datasets before training."
            % "; ".join(problems)
        )


def _require_phase_tracking_capture_sweep(bundle: Path) -> None:
    """Require one consistent SNR-variant source in every frozen capture asset."""

    expected = tuple(float(value) for value in PHASE_TRACKING_CAPTURE_SNR_DB)
    source_path = bundle / "noema_recipe.yaml"
    if not source_path.is_file():
        raise ValueError(
            "The phase-tracking receiver bundle is missing noema_recipe.yaml. "
            "Export the training bundle again before attaching the demo."
        )
    source_recipe = load_recipe(source_path)
    source_matrix = canonicalize_recipe_matrix(source_recipe)
    source_matrix_snr = _finite_numeric_sequence(
        matrix_values_for_step_param(
            source_recipe,
            "wireless_channel",
            "snr_db",
        )
    )
    matrix_is_authoritative = source_matrix.enabled
    problems = []
    if matrix_is_authoritative and source_matrix_snr != expected:
        rendered = (
            "missing" if source_matrix_snr is None else repr(source_matrix_snr)
        )
        problems.append("noema_recipe.yaml matrix declares %s" % rendered)

    plan_path = bundle / "training_plan.yaml"
    if not plan_path.is_file():
        problems.append("training_plan.yaml is missing")
    else:
        plan_payload = _mapping(plan_path)
        plan_capture = plan_payload.get("dataset_capture") or {}
        plan_sweep = (
            plan_capture.get("sweep")
            if isinstance(plan_capture, Mapping)
            else None
        )
        plan_snr = _finite_numeric_sequence(
            plan_sweep.get("wireless_channel.snr_db")
            if isinstance(plan_sweep, Mapping)
            else None
        )
        if matrix_is_authoritative:
            if plan_sweep is not None:
                problems.append(
                    "training_plan.yaml redundantly declares dataset_capture.sweep"
                )
        elif plan_snr != expected:
            rendered = "missing" if plan_snr is None else repr(plan_snr)
            problems.append("training_plan.yaml sweep declares %s" % rendered)

    for relative in (
        "capture_train_recipe.yaml",
        "capture_validation_recipe.yaml",
        "capture_test_recipe.yaml",
    ):
        path = bundle / relative
        if not path.is_file():
            problems.append("%s is missing" % relative)
            continue
        capture_recipe = load_recipe(path)
        capture_matrix = canonicalize_recipe_matrix(capture_recipe)
        matrix_snr = _finite_numeric_sequence(
            matrix_values_for_step_param(
                capture_recipe,
                "wireless_channel",
                "snr_db",
            )
        )
        capture_config = dict(capture_recipe.dataset_capture or {})
        raw_sweep = capture_config.get("sweep")
        sweep_snr = _finite_numeric_sequence(
            raw_sweep.get("wireless_channel.snr_db")
            if isinstance(raw_sweep, Mapping)
            else None
        )
        if matrix_is_authoritative:
            if not capture_matrix.enabled or matrix_snr != expected:
                rendered = "missing" if matrix_snr is None else repr(matrix_snr)
                problems.append("%s matrix declares %s" % (relative, rendered))
            if raw_sweep is not None:
                problems.append(
                    "%s also declares dataset_capture.sweep" % relative
                )
        else:
            if capture_matrix.enabled:
                problems.append("%s unexpectedly declares metadata.matrix" % relative)
            if sweep_snr != expected:
                rendered = "missing" if sweep_snr is None else repr(sweep_snr)
                problems.append("%s sweep declares %s" % (relative, rendered))

    if problems:
        raise ValueError(
            "The phase-tracking receiver demonstration requires exactly one "
            "wireless_channel.snr_db variant definition with values "
            "[-2, 2, 6, 10]. This bundle is not ready: %s. Leave Capture "
            "coordinates blank for the built-in matrix template, enable "
            "Overwrite generated files, export the training bundle again, and "
            "recapture all datasets before training."
            % "; ".join(problems)
        )


def _finite_numeric_sequence(value: Any) -> tuple[float, ...] | None:
    if not isinstance(value, (list, tuple)) or not value:
        return None
    normalized = []
    for item in value:
        if isinstance(item, bool):
            return None
        try:
            number = float(item)
        except (TypeError, ValueError):
            return None
        if not math.isfinite(number):
            return None
        normalized.append(number)
    return tuple(normalized)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Prepare a checked-in demonstration trainer beside a neutral Noema contract."
    )
    parser.add_argument("demo", choices=sorted(DEMO_LOSSES))
    parser.add_argument("bundle", type=Path, help="Workbench-exported training-interface directory")
    parser.add_argument(
        "--project-root",
        type=Path,
        default=Path(__file__).resolve().parents[1],
        help="Noema checkout root (defaults to the root containing this script)",
    )
    args = parser.parse_args()
    try:
        output = prepare_example(args.bundle, args.demo, project_root=args.project_root)
    except ValueError as exc:
        parser.error(str(exc))
    _print_next_steps(output, project_root=args.project_root)
    return 0


def _print_next_steps(output: Path, *, project_root: Path) -> None:
    """Print copyable commands without falling back to an unrelated Python alias."""

    bundle = Path(output).resolve().parent
    working_directory = shlex.quote(str(bundle))
    interpreter = shlex.quote(sys.executable)
    root = Path(project_root).resolve()
    checkout_uses_uv = (root / "pyproject.toml").is_file() and (root / "uv.lock").is_file()
    capture_jobs = _bundle_capture_jobs(bundle)
    print("demo training project attached: %s" % Path(output).resolve())
    print("")
    if capture_jobs and _bundle_captures_are_ready(bundle, capture_jobs):
        print(
            "Captured train, validation, and held-out test datasets are already "
            "ready; the trainer refresh preserved them."
        )
        next_step_label = "Run:"
    elif capture_jobs:
        print("Before training:")
        print(
            "  Return to Workbench > Dataset capture and select Capture all datasets "
            "(or Recapture all datasets)."
        )
        readiness = _capture_readiness_summary(capture_jobs)
        if readiness:
            print("  Wait until all splits are ready: %s." % readiness)
        else:
            print("  Wait until every required split reports ready.")
        next_step_label = "Only then run:"
    else:
        print(
            "No dataset capture is required; this bundle's exported data "
            "contract is ready for the example."
        )
        next_step_label = "Run:"
    print("")
    print(next_step_label)
    if checkout_uses_uv:
        project = shlex.quote(str(root))
        print("  cd %s" % working_directory)
        print(
            "  uv run --project %s --extra onnx python --version"
            "  # must report Python 3.11 through 3.13" % project
        )
        print("  uv run --project %s --extra onnx python train_demo.py" % project)
        print("  uv run --project %s --extra onnx python evaluate_demo.py" % project)
    else:
        print("  cd %s" % working_directory)
        print("  %s --version  # must report Python 3.11 through 3.13" % interpreter)
        print(
            "  Prerequisite: install every package listed in "
            "reference_training/requirements.txt "
            "in this interpreter's environment."
        )
        print("  %s train_demo.py" % interpreter)
        print("  %s evaluate_demo.py" % interpreter)
    print("")
    print(
        "Workbench detects the returned artifact automatically. "
        "After training, return and select Validate returned model."
    )


def _bundle_capture_jobs(bundle: Path) -> list[Dict[str, Any]]:
    manifest_path = bundle / "project_manifest.yaml"
    if not manifest_path.is_file():
        return []
    try:
        manifest = _mapping(manifest_path)
    except (OSError, ValueError, yaml.YAMLError):
        return []
    return _manifest_capture_jobs(manifest)


def _capture_readiness_summary(jobs: list[Dict[str, Any]]) -> str:
    order = {"train": 0, "validation": 1, "test": 2}
    rows = []
    for item in sorted(
        (job for job in jobs if isinstance(job, Mapping)),
        key=lambda job: order.get(str(job.get("split") or ""), 99),
    ):
        split = str(item.get("split") or "")
        label = str(item.get("label") or split.replace("_", " ").title())
        requested = int(item.get("requested_samples") or 0)
        if requested > 0:
            rows.append("%s %s" % (label, format(requested, ",d")))
    return " · ".join(rows)


def _bundle_captures_are_ready(
    bundle: Path,
    jobs: list[Dict[str, Any]],
) -> bool:
    """Recognize complete bundle-owned captures after an in-place refresh."""

    required = {"train", "validation", "test"}
    seen = set()
    for job in jobs:
        if not isinstance(job, Mapping):
            continue
        split = str(job.get("split") or "")
        if split not in required:
            continue
        schema_path = Path(bundle) / "data" / split / "schema.json"
        if not schema_path.is_file():
            return False
        try:
            schema = load_strict_yaml_or_json(schema_path)
        except (OSError, UnicodeError, ValueError):
            return False
        if not isinstance(schema, Mapping):
            return False
        requested = int(job.get("requested_samples") or 0)
        if requested and int(schema.get("captured_samples") or 0) < requested:
            return False
        tap_schemas = schema.get("tap_schemas")
        if not isinstance(tap_schemas, Mapping):
            return False
        present_ids = {str(value) for value in tap_schemas}
        present_references = {
            str(value.get("from"))
            for value in tap_schemas.values()
            if isinstance(value, Mapping) and value.get("from")
        }
        for tap in job.get("expected_taps") or []:
            if not isinstance(tap, Mapping):
                continue
            tap_id = str(tap.get("id") or "")
            reference = str(tap.get("from") or "")
            if tap_id not in present_ids and reference not in present_references:
                return False
        seen.add(split)
    return seen == required


if __name__ == "__main__":
    raise SystemExit(main())
