"""Slow, auditable agentic supervision for Noema experiments."""

from noema_lab.agentic.backends import (
    DecisionBackend,
    DecisionBackendError,
    DecisionRequest,
    DecisionResponse,
    InvalidDecisionActionError,
    OllamaBackend,
    OpenAICompatibleBackend,
    ReplayBackend,
    RuleBasedBackend,
    ScriptedBackend,
    StaticBackend,
    TransformersBackend,
    build_backend,
)
from noema_lab.agentic.contracts import (
    ACTION_TOOL,
    CONTRACT_KIND,
    CONTRACT_SCHEMA_VERSION,
    SUPPORTED_OBSERVATION_FIELDS,
    SUPPORTED_POLICIES,
    ActionContract,
    ActionEnvelope,
    AgenticContract,
    AgenticContractError,
    ObjectiveTieBreaker,
    ProviderConfig,
    action_contract_from_mapping,
    agentic_contract_from_mapping,
    load_agentic_contract,
    parse_action_envelope,
    provider_config_from_mapping,
)
from noema_lab.agentic.harness import (
    AgenticCampaignError,
    replay_agentic_campaign,
    run_agentic_campaign,
    verify_agentic_campaign,
)

__all__ = [
    "ACTION_TOOL",
    "CONTRACT_KIND",
    "CONTRACT_SCHEMA_VERSION",
    "SUPPORTED_OBSERVATION_FIELDS",
    "SUPPORTED_POLICIES",
    "ActionContract",
    "ActionEnvelope",
    "AgenticContract",
    "AgenticContractError",
    "AgenticCampaignError",
    "DecisionBackend",
    "DecisionBackendError",
    "DecisionRequest",
    "DecisionResponse",
    "InvalidDecisionActionError",
    "ObjectiveTieBreaker",
    "OllamaBackend",
    "OpenAICompatibleBackend",
    "ProviderConfig",
    "ReplayBackend",
    "RuleBasedBackend",
    "ScriptedBackend",
    "StaticBackend",
    "TransformersBackend",
    "action_contract_from_mapping",
    "agentic_contract_from_mapping",
    "build_backend",
    "load_agentic_contract",
    "parse_action_envelope",
    "provider_config_from_mapping",
    "replay_agentic_campaign",
    "run_agentic_campaign",
    "verify_agentic_campaign",
]
